### ISSUE TITLE
Error fetching entities from Home Assistant, but different

### ISSUE THREAD

**Issue by KubilayC38** [apop880/photodash#35]
Same scenario as is https://github.com/apop880/photodash/issues/30, but it still does not work after a few days. Restarts, whether of the device, of Home Assistant, or the Add-On did not work. Global settings can be accessed. Long-lived token is set. I added the URL with and without quotation marks because my other URLs work without those marks. So I am unsure whether it works with or without. Doesn't hurt anyone. I also tried it with only one entry, so the problem should not be because the entry is there two times ;)

Set-Up:
- Raspberry Pi 4 with Home Assistant OS
- Core: 2024.1.2
- Supervisor: 2023.12.0
- Operating System: 11.4

HTTP configuration:
```
http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - http://192.168.0.200:8800 # for Photodash Add-On
    - "http://192.168.0.200:8800" # for Photodash Add-On
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

Logs:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "photodash" at "core-mariadb:3306"

The database is already in sync with the Prisma schema.

Running generate... (Use --skip-generate to skip the generators)
Running generate... - Prisma Client
✔ Generated Prisma Client (4.10.1 | library) to ./node_modules/@prisma/client in
 924ms

Listening on 0.0.0.0:3000
```
